FROM python:3.10

WORKDIR /app
COPY src/requirements.txt .
RUN python3 -m pip install -r requirements.txt

COPY src/services/kafka_producers/scraper_stock_xtb.py /app/

CMD ["python", "-u", "scraper_stock_xtb.py"]
