FROM python:3.10-slim

WORKDIR /app

COPY src/requirements_model.txt .
RUN python3 -m pip install -r requirements_model.txt

COPY src/services/models/app.py /app/

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
